### PR TITLE
match domains array length with port array length for cyberfly components

### PR DESCRIPTION
**Pull request by abuvanth**

### CODE REVIEW

**Comment by abuvanth** [comment]
devmarketplace is free for test or need i pay?

**Comment by abuvanth** [comment]
any update

**Review by Cabecinha84 — APPROVED** [review]
ack

**Comment by abuvanth** [comment]
tested working fine.
i suggest you to give an option in config to choose component for main domain.
for my case the first component is mqtt, second node api , third is UI.
In default Flux taking first component for main domain.
after deployment when i click visit app button, nothing open because that main domain configured to MQTT(first component) which is not a web server.

**Pull request merged**
