### PR TITLE
Update marketplaceApps.json

### PR DESCRIPTION
**Pull request by Kyuubi2709**
I added the Nexa Node to the marketplace @TheTrunk @Cabecinha84

### CODE REVIEW

**Review by Cabecinha84 — CHANGES_REQUESTED** [review]
PortSpecs have a typo in first number.
And ports should not use port 39000 as it is used by presearchnode app on marketplace, so the app would not install where that app is running.

**Comment by Kyuubi2709** [comment]
> PortSpecs have a typo in first number. And ports should not use port 39000 as it is used by presearchnode app on marketplace, so the app would not install where that app is running.

I changed the application ports to something else.
I dont see the typo you are referring to. If you mean because of the 7228 before 7227, that is on purpose

**Review by Cabecinha84 — APPROVED** [review]
Ack

**Comment by Cabecinha84** [comment]
PortSpecs was starting at 390000, one extra zero.

**Pull request merged**
